import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Link from 'next/link';

import fetch from "isomorphic-unfetch";

export default function Home() {
  const [address, setAddress] = useState("");
  const [functionName, setFunctionName] = useState("");
  const [functionArguments, setFunctionArguments] = useState("");
  const [blockNumber, setBlockNumber] = useState(0);
  const [abi, setAbi] = useState("");
  const [rpcUrl, setRpcUrl] = useState("");

  const [result, setResult] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    setResult("");
    setError("");
    setLoading(true);
    await sendApiRequest();
  };

  async function sendApiRequest() {
    const payload = {
      address: address,
      functionName: functionName,
      functionArguments: functionArguments,
      blockNumber: blockNumber,
      abi: abi,
      rpcUrl: rpcUrl,
    };
    console.log(payload)
    const response = await fetch("/api/server", {
      method: "POST",
      body: JSON.stringify(payload),
    });
    const data = await response.json();
    setLoading(false);
    setResult(data.stdout);
    setError(data.stderr);
  }

  const renderSubmittedContainer = () => {
    return (
      <div className={styles.result}>
        <h3>Function Result:</h3>
        <p>{result}</p>
      </div>
    );
  };

  const renderErrorContainer = () => {
    return (
      <div className={styles.result}>
        <h3>Error Message:</h3>
        <p>{error}</p>
      </div>
    );
  };

  // Can include validation logic for each parameter if required
  const onAddressChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target;
    setAddress(value);
  };

  const onFunctionNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target;
    setFunctionName(value);
  };

  const onFunctionArgumentChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const { value } = event.target;
    setFunctionArguments(value);
  };

  const onBlockNumberChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target;
    setBlockNumber(Number(value));
  };

  const onAbiChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target;
    setAbi(value);
  };

  const onRpcUrlChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target;
    setRpcUrl(value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Foundry-Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://book.getfoundry.sh/">Foundry</a> Dev Tool
        </h1>

      
          <div className={styles.infoBox}>
            <p className={styles.description}>
              For RPC calls the following fields are required:{" "}
            </p>
            <ol>1*. Address of the contract to query</ol>
            <ol>2*. Function name & return type, e.g balanceOf()(uint256)</ol>
            <ol>3. Argument type and value if any, e.g address 0xcbe..</ol>
            <ol>4*. RPC url</ol>
            <ol>5. Block Number to execute query</ol>
          </div>

          <div className={styles.infoBox}>
            <p className={styles.description}>
              ERC20 <Link className={styles.link} href="/erc20"> Tests </Link>
            </p>
          </div>
 

        <form
          onSubmit={(event) => {
            event.preventDefault();
            handleSubmit();
          }}
        >
          <div className={styles.gridContainer}>
            <div className={styles.grid}>
              <div className={styles.card}>
                <p>Address:</p>
                <input
                  className={styles.input}
                  type="text"
                  placeholder="0xsdsds.."
                  value={address}
                  onChange={onAddressChange}
                />
              </div>
            </div>

            <div className={styles.grid}>
              <div className={styles.card}>
                <p>Function Name:</p>
                <input
                  className={styles.input}
                  type="text"
                  placeholder="totalSupply()(uint256)"
                  value={functionName}
                  onChange={onFunctionNameChange}
                />
              </div>
            </div>
          </div>

          <div className={styles.gridContainer}>
            <div className={styles.grid}>
              <div className={styles.card}>
                <p>Arguments (if any):</p>
                <input
                  className={styles.input}
                  type="text"
                  placeholder="address 0xbe.."
                  value={functionArguments}
                  onChange={onFunctionArgumentChange}
                />
              </div>
            </div>

            <div className={styles.grid}>
              <div className={styles.card}>
                <p>Block Number:</p>
                <input
                  className={styles.input}
                  type="number"
                  placeholder="16237586"
                  value={blockNumber}
                  onChange={onBlockNumberChange}
                />
              </div>
            </div>
          </div>

          <div className={styles.gridContainer}>
            <div className={styles.grid}>
              <div className={styles.card}>
                <p>Contract ABI:</p>
                <input
                  className={styles.input}
                  type="text"
                  placeholder="JSON"
                  value={abi}
                  onChange={onAbiChange}
                />
              </div>
            </div>

            <div className={styles.grid}>
              <div className={styles.card}>
                <p>RPC url:</p>
                <input
                  className={styles.input}
                  type="text"
                  placeholder="https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
                  value={rpcUrl}
                  onChange={onRpcUrlChange}
                />
              </div>
            </div>
          </div>

          <div className={styles.buttonContainer}>
            <button type="submit" className={styles.button}>
              Submit
            </button>
          </div>
        </form>
        {loading ? (
          <div>
            <p>Loading</p>{" "}
            <Image src="/loading.gif" alt="" width={50} height={50} />
          </div>
        ) : (
          ""
        )}
        {result != "" ? renderSubmittedContainer() : ""}
        {error != "" ? renderErrorContainer() : ""}
      </main>
    </div>
  );
}
